-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WithElm.Object.Post exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import WithElm.InputObject
import WithElm.Interface
import WithElm.Object
import WithElm.Scalar
import WithElm.ScalarCodecs
import WithElm.Union


content : SelectionSet String WithElm.Object.Post
content =
    Object.selectionForField "String" "content" [] Decode.string


likes : SelectionSet (Maybe Int) WithElm.Object.Post
likes =
    Object.selectionForField "(Maybe Int)" "likes" [] (Decode.int |> Decode.nullable)


title : SelectionSet String WithElm.Object.Post
title =
    Object.selectionForField "String" "title" [] Decode.string
